
### GET YOUR Account-Group ID

GET https://api.thousandeyes.com/v7/account-groups 
Authorization: Bearer "Your-OAuth-Token-Here"


### GET Agent-ID for "Amsterdam, Netherlands" and "San Francisco, CA"

GET https://api.thousandeyes.com/v7/agents?agentTypes=cloud 
Authorization: Bearer "Your-OAuth-Token-Here"